In [ ]:
# hotel_bookingscsv_path = kagglehub.dataset_download('ahmedsafwatgb20/hotel-bookingscsv')

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('/kaggle/input/hotel-bookingscsv/hotel_bookings.csv')

In [4]:
df.head(5)

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,no,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,7/1/2015
1,Resort Hotel,no,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,7/1/2015
2,Resort Hotel,no,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,7/2/2015
3,Resort Hotel,no,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,7/2/2015
4,Resort Hotel,no,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,7/3/2015

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  object
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(15), object(13)
memory usage: 29.1+ MB

In [6]:
df.describe()

,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

## How many rows are there?

In [7]:
len(df)

119390

## If there is any missing data? If so, which column has the most missing data?

In [8]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

## Drop the company column from the dataset

In [9]:
df.drop('company', axis = 1, inplace = True)

## What are the top 5 most common country codes in the dataset?

In [16]:
df['country'].value_counts().head()

country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
Name: count, dtype: int64

##  who paid the highest ADR (average dialy rate)? How much was their ADR?

In [20]:
df['adr'].head()

0     0.0
1     0.0
2    75.0
3    75.0
4    98.0
Name: adr, dtype: float64

In [22]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [23]:
df.iloc[df['adr'].idxmax()]

hotel                                City Hotel
is_canceled                                 yes
lead_time                                    35
arrival_date_year                          2016
arrival_date_month                        March
arrival_date_week_number                     13
arrival_date_day_of_month                    25
stays_in_weekend_nights                       0
stays_in_week_nights                          1
adults                                        2
children                                    0.0
babies                                        0
meal                                         BB
country                                     PRT
market_segment                    Offline TA/TO
distribution_channel                      TA/TO
is_repeated_guest                             0
previous_cancellations                        0
previous_bookings_not_canceled                0
reserved_room_type                            A
assigned_room_type                            A
booking_changes                               1
deposit_type                         Non Refund
agent                                      12.0
days_in_waiting_list                          0
customer_type                         Transient
adr                                      5400.0
required_car_parking_spaces                   0
total_of_special_requests                     0
reservation_status                     Canceled
reservation_status_date               2/19/2016
Name: 48515, dtype: object

## What is the mean adr across all the hotel stays in the dataset?

In [25]:
round(df['adr'].mean(),2)

101.83

## What is the average number of nights for a stay across the entire dataset?

In [26]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [28]:
df['nights_stay'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']
round(df['nights_stay'].mean(), 2)

3.43

## What is the average total cost for a stay in the dataset? Not average daily cost, but total stay cost. Feel free to round this to 2 decimal points.

In [29]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'nights_stay'],
      dtype='object')

In [36]:
df = df.rename(columns={'nights_stay': 'total_stay'})

In [37]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'total_stay'],
      dtype='object')

In [38]:
df['total_cost'] = df['total_stay'] * df['adr']
round(df['total_cost'].mean(),2)

357.85

## Records with 5 special requests

In [40]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'total_stay',
       'total_cost'],
      dtype='object')

In [41]:
df[df['total_of_special_requests'] == 5]

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_stay,total_cost
7860,Resort Hotel,yes,39,2016,August,36,30,0,5,2,...,NaN,0,Transient,159.00,0,5,Canceled,7/22/2016,5,795.00
11125,Resort Hotel,no,108,2017,April,16,21,4,7,2,...,NaN,0,Transient,85.00,0,5,Check-Out,5/2/2017,11,935.00
14596,Resort Hotel,no,22,2015,July,28,9,0,3,3,...,NaN,0,Transient-Party,180.67,1,5,Check-Out,7/12/2015,3,542.01
14921,Resort Hotel,no,185,2017,February,8,24,2,2,1,...,NaN,0,Transient,39.60,0,5,Check-Out,2/28/2017,4,158.40
14922,Resort Hotel,no,134,2017,April,15,13,0,3,1,...,NaN,0,Transient,61.50,0,5,Check-Out,4/16/2017,3,184.50
24630,Resort Hotel,no,76,2016,May,21,20,2,5,2,...,240.0,0,Transient-Party,127.14,0,5,Check-Out,5/27/2016,7,889.98
27288,Resort Hotel,no,210,2016,August,33,12,4,10,2,...,2.0,0,Contract,106.55,0,5,Check-Out,8/26/2016,14,1491.70
27477,Resort Hotel,no,3,2016,August,35,24,2,5,2,...,240.0,0,Transient,198.86,0,5,Check-Out,8/31/2016,7,1392.02
29906,Resort Hotel,no,47,2016,November,45,5,2,2,2,...,240.0,0,Transient,74.80,0,5,Check-Out,11/9/2016,4,299.20
29949,Resort Hotel,no,24,2017,March,13,29,0,2,2,...,250.0,0,Group,63.00,0,5,Check-Out,3/31/2017,2,126.00
32267,Resort Hotel,no,84,2017,January,3,18,0,2,2,...,240.0,0,Transient,100.50,0,5,Check-Out,1/20/2017,2,201.00
39027,Resort Hotel,no,231,2017,August,31,2,0,4,2,...,240.0,0,Transient,225.00,1,5,Check-Out,8/6/2017,4,900.00
39129,Resort Hotel,no,231,2017,August,31,2,2,4,2,...,240.0,0,Transient,315.33,1,5,Check-Out,8/8/2017,6,1891.98
39525,Resort Hotel,no,178,2017,August,33,14,1,5,2,...,250.0,0,Transient,262.50,0,5,Check-Out,8/20/2017,6,1575.00
70114,City Hotel,yes,51,2017,June,23,9,2,3,2,...,NaN,0,Transient,78.00,0,5,Canceled,5/9/2017,5,390.00
78819,City Hotel,no,30,2015,October,42,14,0,3,2,...,9.0,0,Contract,96.30,0,5,Check-Out,10/17/2015,3,288.90
78820,City Hotel,no,30,2015,October,42,14,0,3,2,...,9.0,0,Contract,96.30,0,5,Check-Out,10/17/2015,3,288.90
78822,City Hotel,no,30,2015,October,42,14,0,3,2,...,9.0,0,Contract,96.30,0,5,Check-Out,10/17/2015,3,288.90
97072,City Hotel,no,54,2016,September,37,10,1,1,2,...,NaN,0,Transient,167.00,0,5,Check-Out,9/12/2016,2,334.00
97099,City Hotel,no,54,2016,September,37,10,1,1,2,...,NaN,0,Transient,139.00,0,5,Check-Out,9/12/2016,2,278.00
97261,City Hotel,no,125,2016,September,37,4,4,6,2,...,7.0,0,Transient,99.79,0,5,Check-Out,9/14/2016,10,997.90
98410,City Hotel,no,3,2016,September,40,26,1,2,3,...,9.0,0,Transient,266.67,0,5,Check-Out,9/29/2016,3,800.01
98674,City Hotel,no,105,2016,September,40,29,1,3,2,...,NaN,0,Transient,96.90,0,5,Check-Out,10/3/2016,4,387.60
99887,City Hotel,no,26,2016,October,43,17,1,2,2,...,14.0,0,Transient,112.88,0,5,Check-Out,10/20/2016,3,338.64
99888,City Hotel,no,26,2016,October,43,17,1,2,2,...,14.0,0,Transient,112.88,0,5,Check-Out,10/20/2016,3,338.64
101569,City Hotel,no,23,2016,November,46,11,1,2,2,...,9.0,0,Transient,124.67,0,5,Check-Out,11/14/2016,3,374.01
102061,City Hotel,no,46,2016,November,47,18,2,3,2,...,7.0,0,Transient,68.07,0,5,Check-Out,11/23/2016,5,340.35
109511,City Hotel,no,36,2017,April,15,10,1,2,2,...,9.0,0,Transient,140.00,0,5,Check-Out,4/13/2017,3,420.00
109590,City Hotel,no,74,2017,April,15,9,2,3,2,...,NaN,0,Transient,116.25,0,5,Check-Out,4/14/2017,5,581.25
110082,City Hotel,no,120,2017,April,16,17,1,4,2,...,9.0,0,Transient-Party,108.00,0,5,Check-Out,4/22/2017,5,540.00
110083,City Hotel,no,120,2017,April,16,17,1,4,1,...,9.0,0,Transient-Party,108.00,0,5,Check-Out,4/22/2017,5,540.00
111909,City Hotel,no,201,2017,May,20,14,2,2,2,...,9.0,0,Transient,125.10,0,5,Check-Out,5/18/2017,4,500.40
111911,City Hotel,no,201,2017,May,20,14,2,2,2,...,9.0,0,Transient,125.10,0,5,Check-Out,5/18/2017,4,500.40
113915,City Hotel,no,51,2017,June,23,9,2,3,2,...,NaN,0,Transient,78.00,0,5,Check-Out,6/14/2017,5,390.00
114770,City Hotel,no,177,2017,June,25,24,2,1,3,...,9.0,0,Transient,166.50,0,5,Check-Out,6/27/2017,3,499.50
114909,City Hotel,no,207,2017,June,25,24,2,2,2,...,9.0,0,Transient,99.00,0,5,Check-Out,6/28/2017,4,396.00
116455,City Hotel,no,219,2017,July,28,14,2,5,1,...,9.0,0,Transient-Party,99.10,0,5,Check-Out,7/21/2017,7,693.70
116457,City Hotel,no,219,2017,July,28,14,2,5,3,...,9.0,0,Transient-Party,156.60,0,5,Check-Out,7/21/2017,7,1096.20
118817,City Hotel,no,217,2017,August,34,21,1,4,2,...,9.0,0,Transient,135.00,0,5,Check-Out,8/26/2017,5,675.00
119161,City Hotel,no,205,2017,August,35,29,0,2,2,...,9.0,0,Transient,99.00,0,5,Check-Out,8/31/2017,2,198.00

## What percentage of hotel stays were classified as 'repeat guests'? hint use : is_repeated_guests

In [42]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'total_stay',
       'total_cost'],
      dtype='object')

In [46]:
df['is_repeated_guest'].unique()

array([0, 1])

In [48]:
(df['is_repeated_guest'].sum() / len(df)) * 100

3.191222045397437

## What are the names of the people who had booked the most number children and babies for their stay

In [49]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'total_stay',
       'total_cost'],
      dtype='object')

In [50]:
df['total_kids'] = df['children'] + df['babies']
df.iloc[df['total_kids'].idxmax()]

hotel                              Resort Hotel
is_canceled                                 yes
lead_time                                    55
arrival_date_year                          2015
arrival_date_month                         July
arrival_date_week_number                     29
arrival_date_day_of_month                    12
stays_in_weekend_nights                       4
stays_in_week_nights                         10
adults                                        2
children                                   10.0
babies                                        0
meal                                         BB
country                                     PRT
market_segment                    Offline TA/TO
distribution_channel                      TA/TO
is_repeated_guest                             0
previous_cancellations                        0
previous_bookings_not_canceled                0
reserved_room_type                            D
assigned_room_type                            D
booking_changes                               2
deposit_type                         No Deposit
agent                                       8.0
days_in_waiting_list                          0
customer_type                          Contract
adr                                      133.16
required_car_parking_spaces                   0
total_of_special_requests                     1
reservation_status                      No-Show
reservation_status_date               7/12/2015
total_stay                                   14
total_cost                              1864.24
total_kids                                 10.0
Name: 328, dtype: object

## How many arrivals took place between the 1st and the 15th of the month?

In [51]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'total_stay',
       'total_cost', 'total_kids'],
      dtype='object')

In [52]:
df['arrival_date_day_of_month'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [55]:
len(df[df['arrival_date_day_of_month'] >= 15])

65434

## Create a table for counts for each day of the week that people arrived?

In [56]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'total_stay',
       'total_cost', 'total_kids'],
      dtype='object')

In [57]:
df.iloc[0]

hotel                             Resort Hotel
is_canceled                                 no
lead_time                                  342
arrival_date_year                         2015
arrival_date_month                        July
arrival_date_week_number                    27
arrival_date_day_of_month                    1
stays_in_weekend_nights                      0
stays_in_week_nights                         0
adults                                       2
children                                   0.0
babies                                       0
meal                                        BB
country                                    PRT
market_segment                          Direct
distribution_channel                    Direct
is_repeated_guest                            0
previous_cancellations                       0
previous_bookings_not_canceled               0
reserved_room_type                           C
assigned_room_type                           C
booking_changes                              3
deposit_type                        No Deposit
agent                                      NaN
days_in_waiting_list                         0
customer_type                        Transient
adr                                        0.0
required_car_parking_spaces                  0
total_of_special_requests                    0
reservation_status                   Check-Out
reservation_status_date               7/1/2015
total_stay                                   0
total_cost                                 0.0
total_kids                                 0.0
Name: 0, dtype: object